name: manki

on:
  workflow_dispatch: {}
  
  pull_request:
    branches:
      - '*'
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true
      
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    env:
      ANKI_CONNECT_URL: "http://localhost:8765"
      API_VERSION: "6"
      ANKI_API_KEY: "apikey"
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ matrix.python-version }}-

      - name: Install dependencies with Poetry
        run: poetry install

      - name: Lint with flake8
        run: poetry run flake8 src/manki --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run tests with Poetry
        run: poetry run pytest test --junitxml=report.xml -v -s --tb=auto

      - name: Upload test report 
        uses: actions/upload-artifact@v3
        with:
          path: report.xml
          name: pytest-report

      - name: Process test report with dorny/test-reporter
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: 'pytest report'
          path: 'report.xml'
          reporter: java-junit
